### ISSUE TITLE
Rework error model

### ISSUE THREAD

**Issue by twuebi** [lakekeeper/lakekeeper#178]
- [ ] Implement internal Error class that has into `ErrorModel` implemented: https://github.com/hansetag/iceberg-rest-server/blob/11e7592b8cc517a314c4c9de42e7f49594833d4d/crates/iceberg-ext/src/catalog/rest/error.rs#L56
- [ ] Make sure `IcebergErrorResponse` stacks are not returned to clients, but log them once they occur

_Originally posted by @c-thiel in https://github.com/hansetag/iceberg-catalog/issues/81#issuecomment-2160493806_

**Comment by c-thiel** [comment]
@twuebi in some parts of the crate we already did some work. All new developments (such as authz) use custom error classes.
Can we close this issue for now?
