### ISSUE TITLE
table creation does not renumber schema field ids

### ISSUE THREAD

**Issue by twuebi** [lakekeeper/lakekeeper#304]
`org.apache.iceberg.catalog.CatalogTests#testBasicCreateTable` and other tests in https://github.com/apache/iceberg/blob/8e2eb9ac2e33ce4bac8956d4e2f099444d03c0e3/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java#L493 use this to create a table:

```java
  protected static final Schema SCHEMA =
      new Schema(
          required(3, "id", Types.IntegerType.get(), "unique ID 🤪"),
          required(4, "data", Types.StringType.get()));
```

and then check for this:

```java
  // This is the actual schema for the table, with column IDs reassigned
  protected static final Schema TABLE_SCHEMA =
      new Schema(
          required(1, "id", Types.IntegerType.get(), "unique ID 🤪"),
          required(2, "data", Types.StringType.get()));
```

**Comment by c-thiel** [comment]
Fixed in the latest version with moving to the upstream `TableMetadataBuilder`
