### ISSUE TITLE
Lakekeeper can not connect with openfga under nginx TLS

### ISSUE THREAD

**Issue by hienduyph** [lakekeeper/lakekeeper#663]
When connect with openfga under nginx TLS, I got an error:

```
{"timestamp":"2024-12-13T03:57:53.747651Z","level":"DEBUG","message":"error: invalid peer certificate: UnknownIssuer","target":"tonic::transport::channel::service::reconnect","filename":"/cargo/registry/src/index.crates.io-6f17d22bba15001f/tonic-0.12.3/src/transport/channel/service/reconnect.rs","line_number":144}
Error: OpenFGA Error: Listing stores failed
OpenFGA Error: Listing stores failed
 
 
 
Caused by:
    OpenFGA Error: Listing stores faile
```

It seem it does not handle certs
A reference that could resolve this.
- https://github.com/hyperium/tonic/pull/445

**Comment by c-thiel** [comment]
Just to get it right:
Lakekeeper connects to OpenFGA via TLS and it's a publicly trusted certificate?

**Comment by c-thiel** [comment]
@hienduyph, fix is merged to main.
Until the next patch release, could you try and use the `latest-main` docker tag?

**Comment by hien-rnd** [comment]
@c-thiel Thanks for quick fixed.
TLS is a publicly trusted cert . I will try and provide feedback tomorrow
