### ISSUE TITLE
S3 folder name is not matching with namespace and table name

### ISSUE THREAD

**Issue by ambaricloud** [lakekeeper/lakekeeper#669]
Is there any setting to match the namespace/table folder name to march with the actual namespace/table name?

"metadata-location": 
"s3://<>/0193c147-ab46-7053-a6ad-4b0554297f90/0193c14e-d119-7320-83a0-3bd66383bf87/metadata/00001-0193c14f-7d2b-7f01-85e9-5586c48c5129.gz.metadata.json",

I would like to see:
"s3://<mybucket>/market/customer/metadata/00001-0193c14f-7d2b-7f01-85e9-5586c48c5129.gz.metadata.json",

**Comment by c-thiel** [comment]
No, and it's currently not a good idea. The catalog is managing names of objects. If we would use the structure you pointed out, we couldn't rename tables (or namespaces, coming in one of the next releases) without touching the storage. There are absolute path references currently in iceberg files, so just renaming the "folder" doesn't work.

If you are interested in this, make sure to upvote the corresponding Iceberg issue, which is a prerequisite:
https://github.com/apache/iceberg/issues/1617

**Comment by c-thiel** [comment]
Let me close this issue for now. Once Iceberg can do this, I am glad to re-open.

**Comment by kesavkolla** [comment]
@c-thiel I have the same problem. I think the problem is slightly different. When we create new table we at least expect the folder names in S3 will match with namespace/table pattern. Instead Lake Keeper is using UUIDs. This will be bit hard to reason about the paths inside S3.
